### ISSUE TITLE
Crash while start the server

### ISSUE THREAD

**Issue by nebotLol** [vp817/RecoveryCompass#1]
PocketMine-MP version: 4.12.0 [Protocol 560]
Git commit: cd233b123bd0a402f266cde889a3bf5412167592
PHP version: 8.0.19
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: RecoveryCompass

Error: Call to a member function getRealPlayer() on null
File: plugins/RecoveryCompass_dev-4.phar/src/EventListener
Line: 79
Type: Error
Backtrace:
#0 pmsrc/src/event/RegisteredListener(60): vp817\EventListener->onQuit(object pocketmine\event\player\PlayerQuitEvent#138877)
#1 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerQuitEvent#138877)
#2 pmsrc/src/player/Player(2138): pocketmine\event\Event->call()
#3 pmsrc/src/player/Player(2117): pocketmine\player\Player->onPostDisconnect(string[249] ..f.... ........ ..6............................f .... .............. ..f......., null)
#4 pmsrc/src/Server(1711): pocketmine\player\Player->disconnect(string[249] ..f.... ........ ..6............................f .... .............. ..f.......)
#5 pmsrc/src/network/mcpe/NetworkSession(252): pocketmine\Server->addOnlinePlayer(object ipad54\netherblocks\player\Player#138652)
#6 (): pocketmine\network\mcpe\NetworkSession->onPlayerCreated(object ipad54\netherblocks\player\Player#138652)
#7 plugins/FakePlayer-master/src/muqsit/fakeplayer/network/FakePlayerNetworkSession(118): ReflectionMethod->invoke(object muqsit\fakeplayer\network\FakePlayerNetworkSession#139105, object ipad54\netherblocks\player\Player#138652)
#8 plugins/FakePlayer-master/src/muqsit/fakeplayer/network/FakePlayerNetworkSession(107): muqsit\fakeplayer\network\FakePlayerNetworkSession->onPlayerCreated(object ipad54\netherblocks\player\Player#138652)
#9 pmsrc/src/promise/Promise(45): muqsit\fakeplayer\network\FakePlayerNetworkSession->muqsit\fakeplayer\network\{closure}(object ipad54\netherblocks\player\Player#138652)
#10 plugins/FakePlayer-master/src/muqsit/fakeplayer/network/FakePlayerNetworkSession(111): pocketmine\promise\Promise->onCompletion(object Closure#138843, object Closure#138880)
#11 pmsrc/src/network/mcpe/NetworkSession(719): muqsit\fakeplayer\network\FakePlayerNetworkSession->createPlayer()
#12 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(142): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
#13 pmsrc/vendor/pocketmine/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#138885)
#14 pmsrc/src/network/mcpe/NetworkSession(418): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#138889)
#15 plugins/FakePlayer-master/src/muqsit/fakeplayer/Loader(164): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#138885, string[4] ....)
#16 plugins/FakePlayer-master/src/muqsit/fakeplayer/Loader(231): muqsit\fakeplayer\Loader->addPlayer(object muqsit\fakeplayer\info\FakePlayerInfo#129018)
#17 plugins/FakePlayer-master/src/muqsit/fakeplayer/Loader(105): muqsit\fakeplayer\Loader->addConfiguredPlayers()
#18 pmsrc/src/scheduler/ClosureTask(57): muqsit\fakeplayer\Loader->muqsit\fakeplayer\{closure}()
#19 pmsrc/src/scheduler/TaskHandler(123): pocketmine\scheduler\ClosureTask->onRun()
#20 pmsrc/src/scheduler/TaskScheduler(141): pocketmine\scheduler\TaskHandler->run()
#21 pmsrc/src/plugin/PluginManager(530): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(int 20)
#22 pmsrc/src/Server(1811): pocketmine\plugin\PluginManager->tickSchedulers(int 20)
#23 pmsrc/src/Server(1700): pocketmine\Server->tick()
#24 pmsrc/src/Server(1061): pocketmine\Server->tickProcessor()
#25 pmsrc/src/PocketMine(328): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#4, string[9] /root/pm/, string[17] /root/pm/plugins/)
#26 pmsrc/src/PocketMine(351): pocketmine\server()
#27 pmsrc(11): require(string[53] phar:///root/pm/PocketMine-MP.phar/src/PocketMine.php)

Code:
[70] 
[71] 	/**
[72] 	 * @param PlayerQuitEvent $event
[73] 	 * @return void
[74] 	 */
[75] 	public function onQuit(PlayerQuitEvent $event): void
[76] 	{
[77] 		$evPlayerName = $event->getPlayer()->getName();
[78] 		$playerCache = $this->getPlayerManager()->getPlayer($evPlayerName);
[79] 		$this->setCompassDirectionToNormal($playerCache, $this->getPlayerDimension($playerCache->getRealPlayer()));
[80] 		$this->getPlayerManager()->removePlayer($evPlayerName);
[81] 	}
[82] 
[83] 	/**
[84] 	 * @param PlayerDeathEvent $event
[85] 	 * @return void
[86] 	 */
[87] 	public function onDeath(PlayerDeathEvent $event): void
[88] 	{
[89] 		$evPlayer = $event->getPlayer();

**Comment by vp817** [comment]
say everything u did

**Comment by nebotLol** [comment]
Now it works. I was using the plugin on fake players, so the plugin could not start.

**Comment by nebotLol** [comment]
but I guess it would still be great to fix it if possible.  =)

**Comment by vp817** [comment]
next time, i know how to fix it
